-- public."Users" definition
CREATE TABLE public."Users" (
	firstname varchar(255) NOT NULL,
	username varchar(255) NOT NULL,
	phone varchar(255) NULL,
	dob date NULL,
	"createdAt" timestamptz NOT NULL,
	"updatedAt" timestamptz NOT NULL,
	"password" varchar NOT NULL,
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	lastname varchar NULL,
	CONSTRAINT users_un UNIQUE (username)
);
CREATE UNIQUE INDEX users_id_idx ON public."Users" USING btree (id);


---public."posts" defination
CREATE TABLE public."posts" (
    id SERIAL PRIMARY KEY,
    user_id INT NOT NULL REFERENCES public."Users"(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT
);

---public."comments" defination
CREATE TABLE public."comments" (
  id SERIAL PRIMARY KEY,
  description TEXT NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
